language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - YABMP_BUILD_TYPE=Release CFLAGS="-m64"
  - YABMP_BUILD_TYPE=Release CFLAGS="-arch x86_64"
  - YABMP_BUILD_TYPE=Release CFLAGS="-m32 -march=i386"
  - YABMP_BUILD_TYPE=Release CFLAGS="-arch i386"
  - YABMP_BUILD_TYPE=Debug   CFLAGS="-m64 -O1 -g -fsanitize=address -fno-omit-frame-pointer"
  - YABMP_BUILD_TYPE=Debug   CFLAGS="-m64 -O0 -g -coverage" LDFLAGS="-coverage"
  
matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: osx
      env: YABMP_BUILD_TYPE=Release CFLAGS="-m64"
    - os: osx
      env: YABMP_BUILD_TYPE=Release CFLAGS="-m32 -march=i386"
    - os: osx
      env: YABMP_BUILD_TYPE=Debug   CFLAGS="-m64 -O1 -g -fsanitize=address -fno-omit-frame-pointer"
    - os: osx
      env: YABMP_BUILD_TYPE=Debug   CFLAGS="-m64 -O0 -g -coverage" LDFLAGS="-coverage"
    - os: linux
      env: YABMP_BUILD_TYPE=Release CFLAGS="-arch x86_64"
    - os: linux
      env: YABMP_BUILD_TYPE=Release CFLAGS="-arch i386"
    - compiler: gcc
      env: YABMP_BUILD_TYPE=Debug   CFLAGS="-m64 -O1 -g -fsanitize=address -fno-omit-frame-pointer"
    - compiler: clang
      env: YABMP_BUILD_TYPE=Release CFLAGS="-m32 -march=i386"
    - compiler: clang
      env: YABMP_BUILD_TYPE=Debug   CFLAGS="-m64 -O0 -g -coverage" LDFLAGS="-coverage"
   
addons:
  apt:
    packages:
      - gcc-multilib
      - zlib1g-dev:i386

before_install:
  - CFLAGS="" pip install --user codecov

install:
  - ./tools/travis-install.sh
  - export PATH=${PWD}/cmake-install/bin:$PATH
  - mkdir build && cd build

script:
  - cmake -G "Unix Makefiles" -DYABMP_BUILD_PNG:BOOL=YES -DCMAKE_BUILD_TYPE=${YABMP_BUILD_TYPE} ..
  - make
  - ctest --output-on-failure
  
after_success:
  - if [ "${LDFLAGS}" == "-coverage" ]; find ./ -type f -name '*.gcno' | awk '{ print "mv "$0" $(dirname "$0")/$(basename "$0" .c.gcno).gcno" }' | bash ; fi
  - if [ "${LDFLAGS}" == "-coverage" ]; find ./ -type f -name '*.gcda' | awk '{ print "mv "$0" $(dirname "$0")/$(basename "$0" .c.gcda).gcda" }' | bash ; fi
  - if [ "${LDFLAGS}" == "-coverage" ]; then codecov ; fi
