language: c

matrix:
  include:
    - os: osx
      compiler: clang
      env: YABMP_BUILD_TYPE=Release CFLAGS="-arch x86_64"
    - os: osx
      compiler: clang
      env: YABMP_BUILD_TYPE=Release CFLAGS="-arch i386"
    - os: linux
      compiler: gcc
      env: YABMP_BUILD_TYPE=Release CFLAGS="-m64"
    - os: linux
      compiler: gcc
      env: YABMP_BUILD_TYPE=Release CFLAGS="-m32 -march=i386"
      addons:
      apt:
        packages:
          - gcc-multilib
          - zlib1g-dev:i386
    - os: linux
      compiler: gcc
      env: YABMP_BUILD_TYPE=Debug CFLAGS="-m64 -O0 -g -coverage" LDFLAGS="-coverage"
    - os: linux
      compiler: clang
      env: YABMP_BUILD_TYPE=Release CFLAGS="-m64"
    - os: linux
      compiler: clang
      env: YABMP_BUILD_TYPE=Debug   CFLAGS="-m64 -O1 -g -fsanitize=address -fno-omit-frame-pointer"

install:
  - ./tools/travis-install.sh
  - export PATH=${HOME}/cmake-install/bin:$PATH
  - mkdir build && cd build

script:
  - cmake -G "Unix Makefiles" -DYABMP_BUILD_PNG:BOOL=YES -DCMAKE_BUILD_TYPE=${YABMP_BUILD_TYPE} ..
  - make
  - ctest --output-on-failure
  - YABMP_USE_CUSTOM_MALLOC=1 ctest --output-on-failure
  - YABMP_USE_MEMORY_STREAM=1 ctest --output-on-failure
  - YABMP_USE_CUSTOM_MALLOC=1 YABMP_USE_MEMORY_STREAM=1 ctest --output-on-failure
  
after_success:
  - if [ "${LDFLAGS}" == "-coverage" ]; then ../tools/travis-coverage.sh ; fi

