language: c
env:
  global:
   - secure: "nPmH3Cfx4ybMlPBVOlY6e42NuRikYWPhUxKSqn2d8QanDAc8QXnhgALff/GJ2pLfEKIpr8RewFGrR5wVsCB0ZY9PHi2MbprI3t1QbxbZs2RQDkBYXLMq13OYU/nYv5ATdsLguH+kcsYKJVqHJnZpF7XHA6RiPNQkkLvykUWwfg81QBchk0YWIT5G043LuLuoQNKwsk8ph9LvTOcFkRQFXksyNKrFA+lwH3Y4J1dx0zhZhXs4b+KjVkv3gxml0vh5wmc/M/j+j1QMM7cDoB5e0bkRP71HeL06X3Z45dBST5qoRp9blWqhu865SfCL8dbz42hi5qBL4t+FOsuIVJ3QBquQsi6i+D4EQ/oFll2tuN+IIQYSlMXEQTGcmentwa8iFcrtBgbV7tRooSSvS3NNDQtzowpoVWTMYeRS+BNtz4a8prb7nuS3zBDEJBoRon/8ntiQOc5lupVdSoXSFpdZDjPNvAINgvy5QQ6CSJV0ZswIq41FsGGK/XeQ8l7yOnE0Kg1pAA5TMw+VTINY3hOgfVJC5CRsbmdDKFA+NadfQAiZOzpjrKo7dBxZw+HpEh61KVtaq4Y9fOb7liIvzxkuJ+Wz2D5IqP38gherTl4IDV1ekwQBKR9Il4EsmT0JOPgZcpUwPJSlphlFUjtuvQc+OZiEJAMLqJFfSl+J08x6S3c="

addons:
  coverity_scan:
    project:
      name: "mayeut/yabmp"
      description: "Build submitted via Travis CI"
    notification_email: m.darbois@gmail.com
    build_command_prepend: "./tools/travis-install.sh && mkdir build && cd build && ${HOME}/cmake-install/bin/cmake -G 'Unix Makefiles' -DYABMP_BUILD_PNG:BOOL=YES .."
    build_command:   "make -j 4"
    branch_pattern: coverity_scan_model

install:
  - echo "Coverity scan build"

script:
  - echo "Coverity scan build"
