version: 0.1.0.{build}
branches:
  except:
  - coverity_scan
skip_tags: true
clone_depth: 50
environment:
  matrix:
  - CI_BUILD_PLATFORM: x86
    CI_VSCOMNTOOLS: $(VS140COMNTOOLS)
  - CI_BUILD_PLATFORM: x64
    CI_VSCOMNTOOLS: $(VS140COMNTOOLS)
  - CI_BUILD_PLATFORM: x86
    CI_VSCOMNTOOLS: $(VS100COMNTOOLS)
install:
- cmd: git submodule update --init --recursive
build_script:
- cmd: >-
    "%CI_VSCOMNTOOLS%..\..\VC\vcvarsall.bat" %CI_BUILD_PLATFORM%

    mkdir build

    cd build

    cmake -G "NMake Makefiles" -DYABMP_BUILD_PNG:BOOL=YES -DYABMP_BUILD_ZLIB:BOOL=YES -DCMAKE_BUILD_TYPE=Release ../

    nmake

    ctest --output-on-failure
test: off
deploy: off
